export const FAVLINKS_REQUEST = 'FAVLINKS_REQUEST';
export const FAVLINKS_SUCCESS = 'FAVLINKS_SUCCESS';
export const FAVLINKS_FAIL = 'FAVLINKS_FAIL';

export const FAVLINKSDEL_REQUEST = 'FAVLINKSDEL_REQUEST';
export const FAVLINKSDEL_SUCCESS = 'FAVLINKSDEL_SUCCESS';
export const FAVLINKSDEL_FAIL = 'FAVLINKSDEL_FAIL';
