//Закладки ссылки
export const FAVLINKS_REQUEST = 'FAVLINKS_REQUEST';
export const FAVLINKS_SUCCESS = 'FAVLINKS_SUCCESS';
export const FAVLINKS_FAIL = 'FAVLINKS_FAIL';

export const FAVLINKSDEL_REQUEST = 'FAVLINKSDEL_REQUEST';
export const FAVLINKSDEL_SUCCESS = 'FAVLINKSDEL_SUCCESS';
export const FAVLINKSDEL_FAIL = 'FAVLINKSDEL_FAIL';


//Заклаки пользователи
export const FAVUSER_REQUEST = 'FAVUSER_REQUEST';
export const FAVUSER_SUCCESS = 'FAVUSER_SUCCESS';
export const FAVUSER_FAIL = 'FAVUSER_FAIL';

export const FAVUSERDEL_REQUEST = 'FAVUSERDEL_REQUEST';
export const FAVUSERDEL_SUCCESS = 'FAVUSERDEL_SUCCESS';
export const FAVUSERDEL_FAIL = 'FAVUSERDEL_FAIL';
